/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginEnseignantRouteImport } from './routes/login.enseignant'
import { Route as LoginEleveRouteImport } from './routes/login.eleve'
import { Route as AppSessionRouteImport } from './routes/_app/session'
import { Route as ApiPublicBootstrapTeacherRouteImport } from './routes/api/public/bootstrap-teacher'
import { Route as AppDashboardEnseignantRouteImport } from './routes/_app/dashboard.enseignant'
import { Route as AppDashboardEleveRouteImport } from './routes/_app/dashboard.eleve'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEnseignantRoute = LoginEnseignantRouteImport.update({
  id: '/login/enseignant',
  path: '/login/enseignant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEleveRoute = LoginEleveRouteImport.update({
  id: '/login/eleve',
  path: '/login/eleve',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBootstrapTeacherRoute =
  ApiPublicBootstrapTeacherRouteImport.update({
    id: '/api/public/bootstrap-teacher',
    path: '/api/public/bootstrap-teacher',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppDashboardEnseignantRoute = AppDashboardEnseignantRouteImport.update({
  id: '/dashboard/enseignant',
  path: '/dashboard/enseignant',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardEleveRoute = AppDashboardEleveRouteImport.update({
  id: '/dashboard/eleve',
  path: '/dashboard/eleve',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session': typeof AppSessionRoute
  '/login/eleve': typeof LoginEleveRoute
  '/login/enseignant': typeof LoginEnseignantRoute
  '/dashboard/eleve': typeof AppDashboardEleveRoute
  '/dashboard/enseignant': typeof AppDashboardEnseignantRoute
  '/api/public/bootstrap-teacher': typeof ApiPublicBootstrapTeacherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session': typeof AppSessionRoute
  '/login/eleve': typeof LoginEleveRoute
  '/login/enseignant': typeof LoginEnseignantRoute
  '/dashboard/eleve': typeof AppDashboardEleveRoute
  '/dashboard/enseignant': typeof AppDashboardEnseignantRoute
  '/api/public/bootstrap-teacher': typeof ApiPublicBootstrapTeacherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/session': typeof AppSessionRoute
  '/login/eleve': typeof LoginEleveRoute
  '/login/enseignant': typeof LoginEnseignantRoute
  '/_app/dashboard/eleve': typeof AppDashboardEleveRoute
  '/_app/dashboard/enseignant': typeof AppDashboardEnseignantRoute
  '/api/public/bootstrap-teacher': typeof ApiPublicBootstrapTeacherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/session'
    | '/login/eleve'
    | '/login/enseignant'
    | '/dashboard/eleve'
    | '/dashboard/enseignant'
    | '/api/public/bootstrap-teacher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/session'
    | '/login/eleve'
    | '/login/enseignant'
    | '/dashboard/eleve'
    | '/dashboard/enseignant'
    | '/api/public/bootstrap-teacher'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/session'
    | '/login/eleve'
    | '/login/enseignant'
    | '/_app/dashboard/eleve'
    | '/_app/dashboard/enseignant'
    | '/api/public/bootstrap-teacher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginEleveRoute: typeof LoginEleveRoute
  LoginEnseignantRoute: typeof LoginEnseignantRoute
  ApiPublicBootstrapTeacherRoute: typeof ApiPublicBootstrapTeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/enseignant': {
      id: '/login/enseignant'
      path: '/login/enseignant'
      fullPath: '/login/enseignant'
      preLoaderRoute: typeof LoginEnseignantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/eleve': {
      id: '/login/eleve'
      path: '/login/eleve'
      fullPath: '/login/eleve'
      preLoaderRoute: typeof LoginEleveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/session': {
      id: '/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/bootstrap-teacher': {
      id: '/api/public/bootstrap-teacher'
      path: '/api/public/bootstrap-teacher'
      fullPath: '/api/public/bootstrap-teacher'
      preLoaderRoute: typeof ApiPublicBootstrapTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/enseignant': {
      id: '/_app/dashboard/enseignant'
      path: '/dashboard/enseignant'
      fullPath: '/dashboard/enseignant'
      preLoaderRoute: typeof AppDashboardEnseignantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/eleve': {
      id: '/_app/dashboard/eleve'
      path: '/dashboard/eleve'
      fullPath: '/dashboard/eleve'
      preLoaderRoute: typeof AppDashboardEleveRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSessionRoute: typeof AppSessionRoute
  AppDashboardEleveRoute: typeof AppDashboardEleveRoute
  AppDashboardEnseignantRoute: typeof AppDashboardEnseignantRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSessionRoute: AppSessionRoute,
  AppDashboardEleveRoute: AppDashboardEleveRoute,
  AppDashboardEnseignantRoute: AppDashboardEnseignantRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginEleveRoute: LoginEleveRoute,
  LoginEnseignantRoute: LoginEnseignantRoute,
  ApiPublicBootstrapTeacherRoute: ApiPublicBootstrapTeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
